const SERVER_URL="https://planowanie-server.onrender.com";
const socket=io(SERVER_URL);let game=null,sortMode=localStorage.getItem("planowanieSort")||"suit";
const $=id=>document.getElementById(id),lobby=$("lobby"),room=$("room"),message=$("message");
const suits={hearts:"♥",diamonds:"♦",clubs:"♣",spades:"♠"},suitNames={hearts:"♥",diamonds:"♦",clubs:"♣",spades:"♠"};
const esc=s=>{const d=document.createElement("div");d.textContent=s;return d.innerHTML};
function cardText(c){return `${c.rank}${suits[c.suit]}`}function cardClass(c){return ["hearts","diamonds"].includes(c.suit)?"card red":"card"}
function showMessage(t,e=false){message.textContent=t||"";message.className=`message${e?" error":""}`}
$("createRoomButton").onclick=()=>{const name=$("playerName").value.trim()||"Gracz";socket.emit("createRoom",{name},r=>r.ok?showGame():showMessage(r.error,true))};
$("joinRoomButton").onclick=()=>{const name=$("playerName").value.trim()||"Gracz",code=$("roomCode").value.trim().toUpperCase();socket.emit("joinRoom",{name,code},r=>r.ok?showGame():showMessage(r.error,true))};
$("copyRoomButton").onclick=async()=>{await navigator.clipboard.writeText(game.code);$("copyRoomButton").textContent="Skopiowano!";setTimeout(()=>$("copyRoomButton").textContent="Kopiuj kod",1200)};
socket.on("connect",()=>showMessage("Połączono z serwerem."));socket.on("connect_error",()=>showMessage("Nie można połączyć z serwerem.",true));socket.on("gameState",s=>{game=s;render()});
function showGame(){lobby.classList.add("hidden");room.classList.remove("hidden");showMessage("")}
function render(){if(!game)return;showGame();if(game.phase==="WAITING")renderLobby();else renderBoard()}
function renderLobby(){$("roomCodeLabel").textContent=game.code;$(`phaseLabel`).textContent=`Oczekiwanie na graczy (${game.players.length}/4)`;$(`players`).innerHTML=game.players.map(p=>`<div class="player-row"><span class="seat">${p.seat}</span><strong>${esc(p.name)}</strong>${p.id===game.hostId?'<span class="host">HOST</span>':''}</div>`).join("");$("startGameButton").classList.toggle("hidden",game.hostId!==game.myId);$("startGameButton").onclick=()=>socket.emit("startGame",r=>{if(!r.ok)showMessage(r.error,true)})}
function sortedHand(){const h=[...game.myHand],so={hearts:0,diamonds:1,clubs:2,spades:3};return sortMode==="suit"?h.sort((a,b)=>so[a.suit]-so[b.suit]||a.value-b.value):h.sort((a,b)=>a.value-b.value||so[a.suit]-so[b.suit])}
function renderBoard(){room.innerHTML=`<div class="game"><header><div><h1>Planowanie Online</h1><span>Pokój ${game.code} · <b>Runda ${game.round}</b> / 7</span></div><div class="phase">${phaseText()}</div></header><div class="players board-players">${game.players.map(playerBox).join("")}</div><div class="play-layout"><main><div class="table" id="table"></div><div class="hand-controls"><b>Twoje karty</b><button id="sortSuit" class="sort ${sortMode==='suit'?'selected':''}">♥♦♣♠ Kolory</button><button id="sortRank" class="sort ${sortMode==='rank'?'selected':''}">2–A Liczby</button></div><div class="hand" id="hand"></div><div id="actions"></div><div id="notice" class="notice"></div></main><aside class="chat"><h3>💬 Czat</h3><div class="chat-list" id="chatList"></div><div class="emoji-row">${["😂","👍","❤️","😎","🔥","👏","😮","😢"].map(e=>`<button data-emoji="${e}">${e}</button>`).join("")}</div><div class="chat-send"><input id="chatInput" maxlength="200" placeholder="Napisz wiadomość…"><button id="sendChat">➤</button></div></aside></div><div class="paper-wrap">${paperSheet()}</div></div>`;
$("table").innerHTML=game.table.length?game.table.map(x=>`<div class="played"><small>${esc(game.players.find(p=>p.id===x.playerId)?.name||"")}</small><div class="${cardClass(x.card)}">${cardText(x.card)}</div></div>`).join(""):'<div class="empty-table">Stół jest pusty</div>';
$("hand").innerHTML=sortedHand().map(c=>`<button class="${cardClass(c)} ${game.currentPlayerId===game.myId&&game.phase==='PLAYING'?'playable':''}" data-card="${c.id}">${cardText(c)}</button>`).join("");
document.querySelectorAll("[data-card]").forEach(b=>b.onclick=()=>socket.emit("playCard",{cardId:b.dataset.card},r=>{if(!r.ok)$("notice").textContent=r.error}));
$("sortSuit").onclick=()=>{sortMode="suit";localStorage.setItem("planowanieSort",sortMode);render()};$("sortRank").onclick=()=>{sortMode="rank";localStorage.setItem("planowanieSort",sortMode);render()};
$("sendChat").onclick=sendChat;$("chatInput").onkeydown=e=>{if(e.key==="Enter")sendChat()};document.querySelectorAll("[data-emoji]").forEach(b=>b.onclick=()=>{$("chatInput").value+=b.dataset.emoji;$("chatInput").focus()});renderChat();renderActions()}
function sendChat(){const i=$("chatInput"),text=i.value.trim();if(text)socket.emit("chatMessage",{text});i.value=""}
function renderChat(){const el=$("chatList");if(!el)return;el.innerHTML=(game.chat||[]).map(m=>`<div class="chat-msg ${m.playerId===game.myId?'mine':''}"><small>${esc(m.name)}</small><div>${esc(m.text)}</div></div>`).join("");el.scrollTop=el.scrollHeight}
function phaseText(){return{BIDDING:"Deklaracje",PLAYING:"Gra",ROUND_RESULT:"Wynik rundy",GAME_RESULT:"Koniec gry"}[game.phase]||game.phase}
function playerBox(p){return `<div class="player-card ${p.id===game.currentPlayerId?'active':''}"><b>${esc(p.name)}</b><span>${p.id===game.myId?'Ty · ':''}Lewy: ${p.tricksWon}</span></div>`}
function renderActions(){const a=$("actions");if(game.phase==="BIDDING"){const me=game.players.find(p=>p.id===game.myId);if(me.bid===null&&game.currentPlayerId===game.myId)a.innerHTML=`<div class="bid"><b>Twoja deklaracja:</b>${Array.from({length:game.cardsPerPlayer+1},(_,i)=>`<button data-bid="${i}">${i}</button>`).join("")}<small>Suma deklaracji musi być ${game.cardsPerPlayer-1} albo ${game.cardsPerPlayer} + 1.</small></div>`;else a.innerHTML=`<p class="center">${me.bid!==null?`Deklaracja: <b>${me.bid}</b>`:`Czekaj na swoją kolej…`}</p>`;document.querySelectorAll("[data-bid]").forEach(b=>b.onclick=()=>socket.emit("submitBid",{bid:Number(b.dataset.bid)},r=>{if(!r.ok)$("notice").textContent=r.error}))}else if(game.phase==="ROUND_RESULT")a.innerHTML=`<div class="result"><h2>Runda ${game.round}</h2><p class="center">Kolejna runda rozpocznie się automatycznie…</p>${roundResult(game.roundScores)}</div>`;else if(game.phase==="GAME_RESULT")a.innerHTML=`<div class="result"><h2>🏁 Koniec gry</h2><p class="center">Wszystkie 7 rund zostało zapisanych.</p></div>`}
function roundResult(s){return`<div class="mini-results">${s.map(x=>`<div><b>${esc(x.name)}</b><span>${x.exact?`${x.bid} → 1 · +${x.score} pkt`:`<s>${x.bid}</s> → 0 pkt`}</span></div>`).join("")}</div>`}
function paperSheet(){const rounds=game.history||[],cols=[7,6,5,4,3,2,1];return`<section class="paper"><div class="paper-title">PLANOWANIE — KARTA WYNIKÓW</div><div class="paper-subtitle">Deklaracja + wynik · trafiona = 1 · nietrafiona = przekreślona</div><table><thead><tr><th>GRACZ</th>${cols.map((n,i)=>`<th>R${i+1}<br><small>${n} kart</small></th>`).join("")}<th>SUMA</th></tr></thead><tbody>${game.players.map(p=>`<tr><th>${esc(p.name)}</th>${cols.map((n,i)=>{const h=rounds.find(x=>x.round===7-i),x=h?.scores.find(y=>y.playerId===p.id);return`<td>${x?`${x.exact?x.bid:`<s>${x.bid}</s>`}<br><span>${x.exact?'1':'0'}</span>`:'—'}</td>`}).join("")}<td class="paper-total">${p.totalScore}</td></tr>`).join("")}</tbody></table><div class="paper-rule">Każda runda ma własną kolumnę: R1, R2, R3, R4, R5, R6, R7.</div></section>`}
