import express from "express";
import http from "http";
import { Server } from "socket.io";
const app=express(), httpServer=http.createServer(app);
const io=new Server(httpServer,{cors:{origin:"*"}});
app.get("/",(_q,res)=>res.json({name:"Planowanie Online",status:"online"}));
app.get("/health",(_q,res)=>res.json({status:"ok"}));
const rooms=new Map();
const SUITS=["hearts","diamonds","clubs","spades"], RANKS=["2","3","4","5","6","7","8","9","10","J","Q","K","A"];
const VALUES=Object.fromEntries(RANKS.map((r,i)=>[r,i+2])), SYMBOLS={hearts:"♥",diamonds:"♦",clubs:"♣",spades:"♠"};
const deck=()=>SUITS.flatMap(s=>RANKS.map(r=>({id:`${r}${s[0].toUpperCase()}`,suit:s,rank:r,value:VALUES[r]})));
const shuffle=a=>{for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const makeCode=()=>{const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let x;do{x=Array.from({length:5},()=>c[Math.floor(Math.random()*c.length)]).join("")}while(rooms.has(x));return x};
const roomOf=id=>[...rooms.values()].find(r=>r.players.some(p=>p.id===id));
const player=(r,id)=>r?.players.find(p=>p.id===id);
function state(r,id){const me=player(r,id);return{code:r.code,hostId:r.hostId,phase:r.phase,round:r.round,cardsPerPlayer:r.cardsPerPlayer,players:r.players.map(p=>({id:p.id,name:p.name,seat:p.seat,bid:p.bid,tricksWon:p.tricksWon,totalScore:p.totalScore})),myId:id,myHand:me?.hand||[],currentPlayerId:r.currentPlayerId,leaderPlayerId:r.leaderPlayerId,table:r.table,lastTrickWinnerId:r.lastTrickWinnerId,roundScores:r.roundScores,history:r.history,final:r.final,chat:r.chat.slice(-80)}}
function emit(r){r.players.forEach(p=>io.to(p.id).emit("gameState",state(r,p.id)))}
function sortHand(r){const so=Object.fromEntries(SUITS.map((s,i)=>[s,i]));r.players.forEach(p=>p.hand.sort((a,b)=>so[a.suit]-so[b.suit]||a.value-b.value))}
function deal(r){const d=shuffle(deck());r.players.forEach(p=>p.hand=[]);for(let i=0;i<r.cardsPerPlayer;i++)for(const p of r.players)p.hand.push(d.pop());sortHand(r);r.phase="BIDDING";r.currentPlayerId=r.leaderPlayerId;r.bidOrder=[]}
function reset(r){r.players.forEach(p=>{p.hand=[];p.bid=null;p.tricksWon=0});r.table=[];r.lastTrick=[];r.lastTrickWinnerId=null;r.roundScores=null;r.currentPlayerId=null;r.phase="DEALING";r.bidOrder=[]}
function startNextRound(r){r.round--;r.cardsPerPlayer=r.round;r.leaderPlayerId=r.lastTrickWinnerId||r.leaderPlayerId;reset(r);deal(r)}
function roundEnd(r){r.roundScores=r.players.map(p=>{const exact=p.bid===p.tricksWon,score=exact?10+p.tricksWon:0;p.totalScore+=score;return{playerId:p.id,name:p.name,bid:p.bid,tricksWon:p.tricksWon,score,totalScore:p.totalScore,exact}});r.history.push({round:r.round,cardsPerPlayer:r.cardsPerPlayer,scores:r.roundScores});if(r.round===1){r.phase="GAME_RESULT";r.final=r.players.map(p=>({playerId:p.id,name:p.name,totalScore:p.totalScore}));return}r.phase="ROUND_RESULT";r.currentPlayerId=null;setTimeout(()=>{if(rooms.get(r.code)===r&&r.phase==="ROUND_RESULT"){startNextRound(r);emit(r)}},3500)}
function trickEnd(r){const lead=r.table[0].card.suit,w=r.table.filter(x=>x.card.suit===lead).reduce((a,b)=>b.card.value>a.card.value?b:a);player(r,w.playerId).tricksWon++;r.lastTrickWinnerId=w.playerId;r.leaderPlayerId=w.playerId;r.table=[];if(r.players.every(p=>p.hand.length===0))roundEnd(r);else{r.phase="PLAYING";r.currentPlayerId=w.playerId}}
function bidsValid(r){const total=r.players.reduce((s,p)=>s+p.bid,0);return total!==r.cardsPerPlayer}
io.on("connection",s=>{
 s.on("createRoom",({name},cb)=>{const r={code:makeCode(),hostId:s.id,phase:"WAITING",round:0,cardsPerPlayer:0,players:[{id:s.id,name:String(name||"Gracz").trim().slice(0,20)||"Gracz",seat:1,hand:[],bid:null,tricksWon:0,totalScore:0}],leaderPlayerId:s.id,currentPlayerId:null,table:[],lastTrick:[],lastTrickWinnerId:null,roundScores:null,history:[],final:null,bidOrder:[],chat:[]};rooms.set(r.code,r);s.join(r.code);cb?.({ok:true,code:r.code});emit(r)});
 s.on("joinRoom",({code,name},cb)=>{const r=rooms.get(String(code||"").trim().toUpperCase());if(!r)return cb?.({ok:false,error:"Pokój nie istnieje."});if(r.players.length>=4)return cb?.({ok:false,error:"Pokój jest pełny."});if(r.phase!=="WAITING")return cb?.({ok:false,error:"Gra już się rozpoczęła."});r.players.push({id:s.id,name:String(name||"Gracz").trim().slice(0,20)||"Gracz",seat:r.players.length+1,hand:[],bid:null,tricksWon:0,totalScore:0});s.join(r.code);cb?.({ok:true,code:r.code});emit(r)});
 s.on("startGame",cb=>{const r=roomOf(s.id);if(!r||r.hostId!==s.id)return cb?.({ok:false,error:"Tylko host może rozpocząć."});if(r.players.length<2)return cb?.({ok:false,error:"Potrzeba co najmniej 2 graczy."});if(52%r.players.length!==0)return cb?.({ok:false,error:"Przy tej liczbie graczy 52 karty nie dzielą się po równo. Gra jest dostępna dla 2 albo 4 graczy."});r.round=52/r.players.length;r.cardsPerPlayer=r.round;r.history=[];r.chat=[];r.leaderPlayerId=r.hostId;reset(r);deal(r);cb?.({ok:true});emit(r)});
 s.on("submitBid",({bid},cb)=>{const r=roomOf(s.id),p=player(r,s.id);if(!r||!p)return cb?.({ok:false,error:"Brak pokoju."});if(r.phase!=="BIDDING"||r.currentPlayerId!==s.id)return cb?.({ok:false,error:"Teraz nie jest Twoja kolej na deklarację."});const n=Number(bid);if(!Number.isInteger(n)||n<0||n>r.cardsPerPlayer)return cb?.({ok:false,error:`Wybierz 0–${r.cardsPerPlayer}.`});if(p.bid!==null)return cb?.({ok:false,error:"Deklaracja została już złożona."});const last=r.bidOrder.length===r.players.length-1;const currentTotal=r.players.reduce((sum,x)=>sum+(x.bid??0),0)+n;if(last&&currentTotal===r.cardsPerPlayer)return cb?.({ok:false,error:`Suma deklaracji nie może wynosić dokładnie ${r.cardsPerPlayer} — nie może być możliwe wzięcie wszystkich lew.`});p.bid=n;r.bidOrder.push(p.id);if(r.players.every(x=>x.bid!==null)){if(!bidsValid(r)){p.bid=null;r.bidOrder.pop();return cb?.({ok:false,error:`Suma deklaracji nie może wynosić dokładnie ${r.cardsPerPlayer}.`})}r.phase="PLAYING";r.currentPlayerId=r.leaderPlayerId}else{const idx=r.players.findIndex(x=>x.id===s.id);r.currentPlayerId=r.players[(idx+1)%r.players.length].id}cb?.({ok:true});emit(r)});
 s.on("playCard",({cardId},cb)=>{const r=roomOf(s.id),p=player(r,s.id);if(!r||!p)return cb?.({ok:false,error:"Brak pokoju."});if(r.phase!=="PLAYING"||r.currentPlayerId!==s.id)return cb?.({ok:false,error:"To nie jest Twoja kolej."});const i=p.hand.findIndex(c=>c.id===cardId);if(i<0)return cb?.({ok:false,error:"Nie masz tej karty."});const card=p.hand[i];if(r.table.length){const lead=r.table[0].card.suit;if(p.hand.some(c=>c.suit===lead)&&card.suit!==lead)return cb?.({ok:false,error:`Musisz dołożyć kolor ${SYMBOLS[lead]}.`})}p.hand.splice(i,1);r.table.push({playerId:s.id,card});if(r.table.length===r.players.length)trickEnd(r);else{const idx=r.players.findIndex(x=>x.id===s.id);r.currentPlayerId=r.players[(idx+1)%r.players.length].id}cb?.({ok:true});emit(r)});
 s.on("chatMessage",({text},cb)=>{const r=roomOf(s.id),p=player(r,s.id);if(!r||!p)return cb?.({ok:false,error:"Brak pokoju."});const clean=String(text||"").trim().slice(0,200);if(!clean)return cb?.({ok:false,error:"Pusta wiadomość."});r.chat.push({id:`${Date.now()}-${s.id}`,playerId:s.id,name:p.name,text:clean,time:Date.now()});emit(r);cb?.({ok:true})});
 s.on("disconnect",()=>{const r=roomOf(s.id);if(!r)return;r.players=r.players.filter(p=>p.id!==s.id);if(!r.players.length){rooms.delete(r.code);return}r.players.forEach((p,i)=>p.seat=i+1);if(r.hostId===s.id)r.hostId=r.players[0].id;if(r.currentPlayerId===s.id)r.currentPlayerId=r.players[0].id;emit(r)})
});
const port=Number(process.env.PORT)||3000;httpServer.listen(port,"0.0.0.0",()=>console.log(`Planowanie Online server listening on port ${port}`));